### ISSUE TITLE
Cannot start on docker machine 1.8.3

### ISSUE THREAD

**Issue by remmelt** [ContainerSolutions/minimesos#102]
The mesos-slave quits immediately and emits this log:

```
434c7bf736e4        mesosphere/mesos-slave:0.22.1-1.0.ubuntu1404    "mesos-slave"            21 seconds ago      Exited (1) 20 seconds ago                                  minimesos-agent-422029971-3070922567
```

```
$ docker logs 434c7bf736e4
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1015 21:56:08.663121  6803 process.cpp:961] libprocess is initialized on 172.17.0.36:5051 for 8 cpus
I1015 21:56:08.663295  6803 logging.cpp:172] INFO level logging started!
I1015 21:56:08.663441  6803 logging.cpp:177] Logging to /var/log
I1015 21:56:08.663467  6803 main.cpp:156] Build: 2015-05-05 06:15:50 by root
I1015 21:56:08.663488  6803 main.cpp:158] Version: 0.22.1
I1015 21:56:08.663506  6803 main.cpp:161] Git tag: 0.22.1
I1015 21:56:08.663524  6803 main.cpp:165] Git SHA: d6309f92a7f9af3ab61a878403e3d9c284ea87e0
Failed to create a containerizer: Could not create DockerContainerizer: Insufficient version of Docker! Please upgrade to >= 1.0.0
```

Running OSX, Boot2docker v1.8.3

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by frankscholten** [comment]
Should be fixed by https://github.com/ContainerSolutions/mini-mesos/issues/107

**Comment by sadovnikov** [comment]
After reading this and comments in Slack... minimesos Java code and (since yesterday) minimesos script   make docker available in containers by sharing certain volumes (files). List of these files might be changing from docker version to version. We need to figure out a way to make the code and script less fragile

**Comment by frankscholten** [comment]
@sadovnikov Good idea. Perhaps we can keep track of all the volumes in the code and create a command to list them like

```
$ minimesos info
```

We could for instance add a read only ``getVolumes()`` method to AbstractContainer in order to print out the volumes details.

@alex-glv: Thoughts?

**Comment by sadovnikov** [comment]
I'm not sure if we need such command. What we need to know is what to share (volumes) per docker version... it would be ideal if docker can be queried about it. However I might be wrong and our dependency on 1.7.1 is due to something else

**Comment by frankscholten** [comment]
Docker can be queried about it with ``docker inspect``. However you would have to inspect all the individual containers.

**Comment by sadovnikov** [comment]
AFAIK, ``docker inspect`` will not tell what you need to share (provide as volumes) to a new container you start in order to make the same docker available in that container: binaries, cgroup files, etc. When ``minimesos`` script runs, there is no container to inspect yet. Therefore we just guessing volumes we need to provide
