### ISSUE TITLE
Select the right Docker binary version in Mesos Agent

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#324]

**Comment by alex-glv** [comment]
We can pull a static docker binary of the appropriate version when running minimesos up, put it into .minimesos directory and link it to the agents.

I think the reason why the docker binary was baked into the agent images because some people had dynamically linked docker binary which failed to execute from the agent.

Pulling the static binary on minimesos up solves the issue and also doesn't require fixed version binary to be in the images.

**Comment by frankscholten** [comment]
Closing. This one is no longer relevant since the volume to the docker binary has been removed.
