### ISSUE TITLE
mixing --debug and exposePorts

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#370]
the `if [ "$#" -gt 0 -a "$1" = up ]; then` line in `bin/minimesos` fails, when user executes `./bin/minimesos --debug up`

**Comment by alex-glv** [comment]
There are two issues here:
 - Naive check for the command=up, where 'up' is expected as the first arguments, while flags are technically allowed in nearly every position
 - The actual error is in jCommander, that fails because of the same reason.

Looking into jcommander to see if it can work properly with flags

**Comment by frankscholten** [comment]
@alex-glv Is this still relevant? The code you are pointing to has changed

**Comment by frankscholten** [comment]
No longer relevant since code has changed since then.
